<a href="https://colab.research.google.com/github/Cookie4686/CEDT-Intern-Map/blob/main/Internship_Map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import json
import pprint
import pandas as pd
import numpy as np
import time
import datetime

# Fetch All Available Application

In [ ]:
from google.colab import userdata
# Session determine the available application based on student's current year
session_id = userdata.get(' session_id')
# Athena Session Cookie from the internship web
cookie = userdata.get('cookie')

In [ ]:
search_query="onlyBookmarked=false&onlyAvailablePositions=true"

# Get total item count first
data_info = requests.get(
  url= f'https://cedtintern.cp.eng.chula.ac.th/api/sessions/{session_id}/openings?search=&page=1&limit=1&{search_query}',
  headers={
   "cookie": cookie
})
total_item_count = data_info.json()['meta']['totalItem']

# Get All Remaining Items
data_info = requests.get(
  url= f'https://cedtintern.cp.eng.chula.ac.th/api/sessions/{session_id}/openings?search=&page=1&limit={total_item_count}&{search_query}',
  headers={
   "cookie": cookie
})
data = data_info.json()
application_df = pd.DataFrame(data['items'])
application_df

,openingId,sessionId,company,title,description,quota,openForCooperativeInternship,compensationAmount,compensationType,workingCondition,...,officeAddressLine1,officeAddressLine2,recruitmentContactChannel,openingDetailContactChannel,startDate,endDate,isPublished,isAcceptingApplication,inStudentDraftCount,isBookmarked
0,1046,5,"{'companyId': 42, 'companyNameTh': 'บริษัท ดีม...",Data Analyst Internship,<h3><strong>Job Description:</strong></h3><ul>...,1,True,NaN,None,None,...,BTS Surasak Thai CC tower,,boonyarin.p@dmit.co.th,ID:Hr.dmit,None,None,True,True,8,False
1,1072,5,"{'companyId': 114, 'companyNameTh': 'บริษัท โก...",Internship Automate Tester,"<p><strong style=""color: rgb(28, 28, 34);"">Job...",1,True,200.0,"{'compensationTypeId': 1, 'compensationType': ...",On-Site,...,"อาคาร FYI Center, Tower 2 ชั้น 12th Floor ห้...",,https://jobs.empeo.com/Gofive/245717,Email: Work@gofive.co.th\nDM Gofive Social Med...,None,None,True,True,5,False
2,1075,5,"{'companyId': 114, 'companyNameTh': 'บริษัท โก...",Internship Flutter Mobile Developer,"<p><strong style=""color: rgb(28, 28, 34);"">Job...",2,True,NaN,None,None,...,"อาคาร FYI Center, Tower 2 ชั้น 12th Floor ห้...",,https://jobs.empeo.com/Gofive/249298,Email: Work@gofive.co.th\nDM Gofive Social Med...,None,None,True,True,2,False
3,1077,5,"{'companyId': 114, 'companyNameTh': 'บริษัท โก...",Internship Wordpress Developer,"<p><strong style=""color: rgb(28, 28, 34);"">ภาพ...",2,True,NaN,None,None,...,"อาคาร FYI Center, Tower 2 ชั้น 12th Floor ห้...",,https://jobs.empeo.com/Gofive/12958,Email: Work@gofive.co.th\nDM Gofive Social Med...,None,None,True,True,1,False
4,1092,5,"{'companyId': 97, 'companyNameTh': 'บริษัท เน็...",Software Developer,<p><strong>หน้าที่ความรับผิดชอบสำหรับนักศึกษาฝ...,3,False,400.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,...,"เลขที่ 719/5-8,9 ถนน พระรามที่ 6 แขวง ปทุมวัน ...",Google map : https://goo.gl/maps/wSYBUN1NWDARL...,Recruit@netbay.co.th,Phattaraporn@netbay.co.th,None,None,True,True,18,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,1800,5,"{'companyId': 5, 'companyNameTh': 'ธนาคาร เกีย...",Software Engineer,<p><strong>Software Engineer (Full Stack)</str...,2,False,350.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,...,อาคาร อาคารเคเคพี ทาวเวอร์ เลขที่ 209 ถนน ถนนส...,,arisa.pasa@kkpfg.com,arisa.pasa@kkpfg.com,None,None,True,True,6,True
168,1801,5,"{'companyId': 5, 'companyNameTh': 'ธนาคาร เกีย...",Software Quality Assurance Engineer (QA),<p><strong>Software Quality Assurance Engineer...,3,False,350.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,...,อาคาร อาคารเคเคพี ทาวเวอร์ เลขที่ 209 ถนน ถนนส...,,arisa.pasa@kkpfg.com,arisa.pasa@kkpfg.com,None,None,True,True,5,False
169,1802,5,"{'companyId': 5, 'companyNameTh': 'ธนาคาร เกีย...",Database Management (DBA) (ฝึกงาน+สหกิจศึกษา),<p><strong>As a Database Administrator (DBA)</...,1,True,350.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,...,อาคาร อาคารเคเคพี ทาวเวอร์ เลขที่ 209 ถนน ถนนส...,,kangsadan.inta@kkpfg.com,kangsadan.inta@kkpfg.com,None,None,True,True,4,False
170,1803,5,"{'companyId': 5, 'companyNameTh': 'ธนาคาร เกีย...",Business Analyst (ฝึกงาน+สหกิจศึกษา),<p><strong>Position: Business Analyst</strong>...,6,True,350.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,...,อาคาร อาคารเคเคพี ทาวเวอร์ เลขที่ 209 ถนน ถนนส...,,prapapan.kasp@kkpfg.com,prapapan.kasp@kkpfg.com,None,None,True,True,11,False
171,1804,5,"{'companyId': 5, 'companyNameTh': 'ธนาคาร เกีย...",Data Engineer Internship,<p><strong>About the role</strong></p><p>KKP’s...,5,False,350.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,...,อาคาร อาคารเคเคพี ทาวเวอร์ เลขที่ 209 ถนน ถนนส...,,suchada.arun@kkpfg.com,suchada.arun@kkpfg.com,None,None,True,True,17,False

In [ ]:
data_info = requests.get(
  url= f'https://cedtintern.cp.eng.chula.ac.th/api/common/opening-tags?sessionId={session_id}',
  headers={
   "cookie": cookie
})
tag_df = pd.DataFrame(data_info.json())
tag_df

     tagId             tagName
0       73              Python
1       41           Developer
2       86                  AI
3       29                 SQL
4        4              Intern
..     ...                 ...
583    817            Azure ML
584    430  Prompt Engineering
585    645   Java, Spring Boot
586    826          Databricks
587    651               Rails

[588 rows x 2 columns]

In [ ]:
tag_df.to_json('tags.json', orient='records')

In [ ]:
application_df.drop(columns=['sessionId', 'isBookmarked', 'isPublished'], inplace=True, errors='ignore')

In [ ]:
application_df.columns

Index(['openingId', 'company', 'title', 'description', 'quota',
       'openForCooperativeInternship', 'compensationAmount',
       'compensationType', 'workingCondition', 'requirements', 'tags',
       'officeName', 'officeAddressLine1', 'officeAddressLine2',
       'recruitmentContactChannel', 'openingDetailContactChannel', 'startDate',
       'endDate', 'isAcceptingApplication', 'inStudentDraftCount'],
      dtype='object')

# Search The Address Location

In [ ]:
application_df['officeAddressLine1'] = application_df['officeAddressLine1'].apply(lambda x : " ".join(x.split()) )

In [ ]:
# Beware of google's bot detection on high usage
# When search in google map it will return coordinate to the web browser to shift the map there
# We locate that coordinate and store it

# Return ['longitude', 'latitude']
def search_location(address, verbose=False):
  address.replace('\n', ' ')
  if address and address != 'ไม่ระบุ':
    data_info = requests.get(
      url= f'https://www.google.com/search?tbm=map&hl=th&gl=th&q={address}',
    )
    text = data_info.text
    # text = text.replace('""','"')

    try:
      null = np.nan
      data = eval(text.removeprefix(")]}'"))
      res = data[1][0][1:]
      if verbose: print("Location Extract Result", res)
      return float(res[0]), float(res[1])
    except:
      print(text)
      return [np.nan, np.nan]

  return [np.nan, np.nan]

In [ ]:
address_group = application_df.groupby('officeAddressLine1')

address_df = pd.DataFrame(data=[],columns=['address', 'longitude', 'latitude'])
for address, _ in address_group:
  coords = search_location(address)
  row = pd.DataFrame(data=[[address, coords[0], coords[1]]], columns=['address', 'longitude', 'latitude'])
  address_df = pd.concat([address_df, row], axis=0, copy=False)

address_df

/tmp/ipykernel_139/3796223713.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  address_df = pd.concat([address_df, row], axis=0, copy=False)

)]}'
[["Location : ห้องปฏิบัติการ ISL2 ชั้น 20 อาคารเจริญวิศวกรรม และ 287 ซอย อ่อนนุช 17 แยก 16 แขวงสวนหลวง เขตสวนหลวง กรุงเทพมหานคร 10250",[[null,null,null,null,null,null,null,null,"LOGsaZOLLb3Ip84P94bFoA0","0ahUKEwiT0ZP3oo-TAxU95MkDHXdDEdQQmBkIAigA",null,null,["0ahUKEwiT0ZP3oo-TAxU95MkDHXdDEdQQ42oIAygA","/search?q\u003dLocation+:+%E0%B8%AB%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%9B%E0%B8%8F%E0%B8%B4%E0%B8%9A%E0%B8%B1%E0%B8%95%E0%B8%B4%E0%B8%81%E0%B8%B2%E0%B8%A3+ISL2+%E0%B8%8A%E0%B8%B1%E0%B9%89%E0%B8%99+20+%E0%B8%AD%E0%B8%B2%E0%B8%84%E0%B8%B2%E0%B8%A3%E0%B9%80%E0%B8%88%E0%B8%A3%E0%B8%B4%E0%B8%8D%E0%B8%A7%E0%B8%B4%E0%B8%A8%E0%B8%A7%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%A1+%E0%B9%81%E0%B8%A5%E0%B8%B0+287+%E0%B8%8B%E0%B8%AD%E0%B8%A2+%E0%B8%AD%E0%B9%88%E0%B8%AD%E0%B8%99%E0%B8%99%E0%B8%B8%E0%B8%8A+17+%E0%B9%81%E0%B8%A2%E0%B8%81+16+%E0%B9%81%E0%B8%82%E0%B8%A7%E0%B8%87%E0%B8%AA%E0%B8%A7%E0%B8%99%E0%B8%AB%E0%B8%A5%E0%B8%A7%E0%B8%87+%E0%B9%80%E0%B8%82%E0%B8%95%E0%B8%AA%E0%B8%A7%E0%B8%99%E0%B8%AB%E0%B8%A5%E0%B8%A7%E0%B8%87+%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%9E%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%A3+10250\u0026hl\u003dth\u0026authuser\u003d0"],null,null,null,null,null,[]]],null,null,null,null,null,null,null,null,null,0],null,null,null,null,null,null,"LOGsaZOLLb3Ip84P94bFoA0",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,[2],null,null,null,null,null,null,null,"Q2dBd0Fn",null,null,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,[0],null,null,null,null,null,null,null,"0ahUKEwiT0ZP3oo-TAxU95MkDHXdDEdQQmRkIAQ"]

                                              address   longitude   latitude
0   126/9 ซอย สุขุมวิท 63 (เอกมัย) แขวงคลองตันเหนื...  100.586465  13.728673
0   1284, 1286, 1288, 1290 Ladprao Rd., Chomphon, ...  100.595701  13.804684
0   140 Moo2, BangPa-in Industrial Estate, Udomsor...  100.591079  14.218785
0   140/1 Kian Gwan Building 2, 9th Floor, Witthay...  100.545668  13.731105
0   140/1 Kian Gwan Building2 18th Floor, Wireless...  100.545986  13.731336
..                                                ...         ...        ...
0   เลขที่ 90 อาคารซีดับเบิ้ลยู ทาวเวอร์ ชั้น 33,3...  100.573739  13.769889
0                                ใกล้สามย่านมิตรทาวด์  100.528300  13.733543
0                   ใกล้สามย่านมิตรทาวด์ หรือ อ่อนนุช  100.569581  13.724311
0    ใกล้สามย่านมิตรทาวด์ หรือ อ่อนนุช หรือนอกสถานที่  100.564642  13.719628
0                                             ไม่ระบุ         NaN        NaN

[91 rows x 3 columns]

In [ ]:
for _, row in address_df.iterrows():
  filter_idx = application_df['officeAddressLine1'] == row['address']
  application_df.loc[filter_idx, ['latitude', 'longitude']] = [row['latitude'], row['longitude']]
application_df.sample(3)

,openingId,company,title,description,quota,openForCooperativeInternship,compensationAmount,compensationType,workingCondition,requirements,...,officeAddressLine1,officeAddressLine2,recruitmentContactChannel,openingDetailContactChannel,startDate,endDate,isAcceptingApplication,inStudentDraftCount,latitude,longitude
128,1720,"{'companyId': 84, 'companyNameTh': 'บริษัท เดอ...",Business Analyst,<p>•Collaborate with stakeholders to define bu...,1,False,NaN,None,None,None,...,อาคาร AIA Sathorn tower ชั้น 15th floor เลขที่...,เข้าออฟฟิศแค่ อังคารกับวันศุกร์ 2 วัน ที่เหลือ...,,,None,None,True,6,13.720226,100.526372
170,1803,"{'companyId': 5, 'companyNameTh': 'ธนาคาร เกีย...",Business Analyst (ฝึกงาน+สหกิจศึกษา),<p><strong>Position: Business Analyst</strong>...,6,True,350.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,อาคาร อาคารเคเคพี ทาวเวอร์ เลขที่ 209 ถนน ถนนส...,,prapapan.kasp@kkpfg.com,prapapan.kasp@kkpfg.com,None,None,True,11,13.745039,100.562361
13,1173,"{'companyId': 51, 'companyNameTh': 'บริษัท โกซ...",Full Stack Developer,<h3><strong>Job Title:</strong> Full Stack Dev...,1,False,NaN,None,Hybrid,None,...,อาคาร อาคารเดอะธารา ชั้น 8-10 เลขที่ 58/28 ถนน...,สามารถเดินทางได้ด้วยรถไฟฟ้าสายสีชมพู สถานีแจ้ง...,P'Pok 061-129-1993,P'Pok 061-129-1993,None,None,True,3,13.901553,100.531340

In [ ]:
application_df.isna().sum()

openingId                         0
company                           0
title                             0
description                       2
quota                             0
openForCooperativeInternship      0
compensationAmount               66
compensationType                 59
workingCondition                 12
requirements                     88
tags                              0
officeName                        0
officeAddressLine1                0
officeAddressLine2                0
recruitmentContactChannel         0
openingDetailContactChannel       0
startDate                       100
endDate                         101
isAcceptingApplication            0
inStudentDraftCount               0
latitude                          9
longitude                         9
dtype: int64

In [ ]:
application_df[application_df['latitude'].isna()]

,openingId,company,title,description,quota,openForCooperativeInternship,compensationAmount,compensationType,workingCondition,requirements,...,officeAddressLine1,officeAddressLine2,recruitmentContactChannel,openingDetailContactChannel,startDate,endDate,isAcceptingApplication,inStudentDraftCount,latitude,longitude
46,1386,"{'companyId': 137, 'companyNameTh': 'บริษัท เว...",Internship Program: Spatial AI Engineer,<h1><strong>Program Overview</strong></h1><p>T...,8,False,0.0,"{'compensationTypeId': 5, 'compensationType': ...",Hybrid,<p><br></p><p>Duration: 10 Weeks</p><p><br></p...,...,Location : ห้องปฏิบัติการ ISL2 ชั้น 20 อาคารเจ...,,hr@vaam.co.th \nnarit@vaam.co.th,,None,None,True,5,NaN,NaN
47,1391,"{'companyId': 154, 'companyNameTh': 'บริษัท โต...",Application System Analyst,<p><strong>- Lead collaboration with domestic ...,1,False,400.0,"{'compensationTypeId': 1, 'compensationType': ...",On-Site,None,...,ไม่ระบุ,,,,2026-05-04T17:00:00.000Z,2026-07-30T17:00:00.000Z,True,8,NaN,NaN
62,1475,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",Application Development,<ul><li>ร่วมพัฒนา ออกแบบ และปรับปรุงแอปพลิเคชั...,8,True,500.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,23,NaN,NaN
63,1478,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",Business Analyst,<ul><li>ร่วมเก็บรวบรวมและวิเคราะห์ความต้องการข...,3,True,400.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,21,NaN,NaN
64,1480,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",IOT Engineer,<ul><li>สนับสนุนทีม IoT ในการพัฒนาและทดสอบโซลู...,4,True,400.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,13,NaN,NaN
65,1481,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",UX/UI Designer,<ul><li>ร่วมวิเคราะห์ความต้องการของผู้ใช้ (Use...,3,True,400.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,11,NaN,NaN
163,1795,"{'companyId': 186, 'companyNameTh': 'บริษัท เร...",ASEAN 1967 (SEA Bridge Next Gen Fellowship Pro...,<p><strong>What ASEAN 1967<em> Fellowship</em>...,5,True,NaN,None,Hybrid,"<p><strong style=""color: rgba(84,84,84,var(--O...",...,ไม่ระบุ,,SEA Bridge | really Corp.\nHelping innovators ...,SEA Bridge | really Corp.\nHelping innovators ...,None,None,True,3,NaN,NaN
164,1796,"{'companyId': 186, 'companyNameTh': 'บริษัท เร...",Technical Assistant,<p>This role supports project teams within the...,5,True,NaN,None,Hybrid,None,...,ไม่ระบุ,,,,None,None,True,2,NaN,NaN
165,1797,"{'companyId': 186, 'companyNameTh': 'บริษัท เร...",Venture Creation (SEA Bridge Next Gen Fellowsh...,<p><strong>What Venture Creation<em> Fellowshi...,5,True,NaN,None,Hybrid,"<p><strong style=""background-color: transparen...",...,ไม่ระบุ,,SEA Bridge | really Corp.\nHelping innovators ...,SEA Bridge | really Corp.\nHelping innovators ...,None,None,True,1,NaN,NaN

In [ ]:
application_df.to_json('application_list.json', orient='records')

In [ ]:
lastUpdate = datetime.datetime.today().strftime("%d %B %Y, %H:%M")
applications = application_df.to_json(orient="records")
tags = tag_df.to_json(orient='records')

with open('data.json', 'w') as file:
  file.write('{'f'"lastUpdate":"{lastUpdate}","applications":{applications},"tags":{tags}''}')

# Read old scraped data

In [ ]:
%pip install pydeck
import pydeck as pdk

Collecting pydeck
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: jinja2>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pydeck) (3.1.6)
Requirement already satisfied: numpy>=1.16.4 in /usr/local/lib/python3.12/dist-packages (from pydeck) (2.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10.1->pydeck) (3.0.3)
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 60.3 MB/s eta 0:00:00
Installing collected packages: pydeck
Successfully installed pydeck-0.9.1

In [ ]:
old_df = pd.read_json('application_list.json')

In [ ]:
filtered_df = old_df[old_df['latitude'].isna() != True]

layer = pdk.Layer(
    "ScatterplotLayer",
    filtered_df,
    get_position=['longitude', 'latitude'],
    get_radius=100,
    get_fill_color=[255, 140, 0],
    pickable=True,
)

view_state = pdk.ViewState(
    latitude=filtered_df['latitude'].mean(),
    longitude=filtered_df['longitude'].mean(),
    zoom=12
)

pdk.Deck(
    layers=[layer],
    initial_view_state=view_state,
    tooltip={"html": """
      <div style="max-width: 75vw;">
        <p style="font-weight: bold; text-color: white;">{title}</p>
        <p>{description}</p>
        <p>{workingCondition}, {compensationAmount} Baht</p>
        <p>{officeAddressLine1}</p>
      </div>
    """}
)

{
  "initialViewState": {
    "latitude": 13.744588486477987,
    "longitude": 100.55987784402518,
    "zoom": 12
  },
  "layers": [
    {
      "@@type": "ScatterplotLayer",
      "data": [
        {
          "company": {
            "companyId": 42,
            "companyNameEn": "Demeter ICT",
            "companyNameTh": "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e14\u0e35\u0e21\u0e35\u0e40\u0e15\u0e2d\u0e23\u0e4c \u0e44\u0e2d\u0e0b\u0e35\u0e17\u0e35 \u0e08\u0e33\u0e01\u0e31\u0e14",
            "facebook": "https://www.facebook.com/demeterict",
            "line": "hr.dmit",
            "logoUrl": "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/0f45a453-1dad-4cd3-b6ff-c80761b24119?v=1701072977024",
            "website": "https://www.dmit.co.th/en/homepage/"
          },
          "compensationAmount": NaN,
          "compensationType": null,
          "description": "<h3><strong>Job Description:</strong></h3><ul><li>Assist in analyzing and cleaning large datasets.</li><li>Contribute to the development and maintenance of dashboards and reports.</li><li>Collaborate with cross-functional teams to provide data-driven insights.</li><li>Support data collection processes and documentation.</li><li>Identify actionable insights and suggest recommendations for data-driven marketing campaigns.</li><li>Interact and collaborate with product and marketing managers to provide impactful analysis and insights that align with business objectives.</li><li>Provide business requirements and collaborate with internal teams on a data capture strategy that will support advanced analysis and insights on consumer behavior.</li></ul><p><br></p>",
          "endDate": null,
          "inStudentDraftCount": 5,
          "isAcceptingApplication": true,
          "latitude": 13.7184359,
          "longitude": 100.5215777,
          "officeAddressLine1": "BTS Surasak Thai CC tower",
          "officeAddressLine2": "",
          "officeName": "\u0e2a\u0e33\u0e19\u0e31\u0e01\u0e07\u0e32\u0e19\u0e43\u0e2b\u0e0d\u0e48",
          "openForCooperativeInternship": true,
          "openingDetailContactChannel": "ID:Hr.dmit",
          "openingId": 1046,
          "quota": 1,
          "recruitmentContactChannel": "boonyarin.p@dmit.co.th",
          "requirements": null,
          "startDate": null,
          "tags": [],
          "title": "Data Analyst Internship",
          "workingCondition": null
        },
        {
          "company": {
            "companyId": 150,
            "companyNameEn": "CHOCO CARD ENTERPRISE Co., Ltd.",
            "companyNameTh": "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e0a\u0e47\u0e2d\u0e04\u0e42\u0e01\u0e49 \u0e04\u0e32\u0e23\u0e4c\u0e14 \u0e40\u0e2d\u0e47\u0e19\u0e40\u0e15\u0e2d\u0e23\u0e4c\u0e44\u0e1e\u0e23\u0e2a\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14 (ChocoCRM)",
            "facebook": "https://www.facebook.com/chococrmofficial",
            "line": "",
            "logoUrl": "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/074e2844-51b4-4f3f-99b1-cc81e44ccf27?v=1761047535641",
            "website": "https://chococrm.com/"
          },
          "compensationAmount": 200.0,
          "compensationType": {
            "compensationType": "\u0e1a\u0e32\u0e17/\u0e27\u0e31\u0e19",
            "compensationTypeId": 1
          },
          "description": "<ul><li>Planning, designing and developing web applications in terms of CRM (Customer Relationship Management), Data Management Platform CDP (Customer Data Platform) and POS (Point of Sale) in the back of the house. (Back-office)</li><li>Design database, basic SQL commands, write API (CRUD) with .Net Core</li><li>Develop and maintain pragmatic high-quality software to support business requirements.</li><li>Work closely with Project Managers, Product Owners and Business Analyst to understand business goals and system requirements</li><li>Work closely with Quality Assurance Team to create practical use cases &amp; scenario which become service best practices</li><li>Work with Technology team to build a maintainable technology infrastructure including build &amp; testing environment.</li><li>Able to learn and research technology for improve skill and problem solving.</li></ul>",
          "endDate": "2026-07-30T17:00:00.000Z",
          "inStudentDraftCount": 1,
          "isAcceptingApplication": true,
          "latitude": 13.6928903,
          "longitude": 100.607012,
          "officeAddressLine1": "\u0e40\u0e25\u0e02\u0e17\u0e35\u0e48 2150/4 \u0e16\u0e19\u0e19 \u0e2a\u0e38\u0e02\u0e38\u0e21\u0e27\u0e34\u0e17 \u0e41\u0e02\u0e27\u0e07 \u0e1e\u0e23\u0e30\u0e42\u0e02\u0e19\u0e07 \u0e40\u0e02\u0e15 \u0e1a\u0e32\u0e07\u0e08\u0e32\u0e01 \u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14 \u0e01\u0e23\u0e38\u0e07\u0e40\u0e17\u0e1e\u0e21\u0e2b\u0e32\u0e19\u0e04\u0e23 10260",
          "officeAddressLine2": "\u0e2a\u0e32\u0e21\u0e32\u0e23\u0e16\u0e40\u0e14\u0e34\u0e19\u0e08\u0e32\u0e01\u0e23\u0e16\u0e44\u0e1f\u0e1f\u0e49\u0e32 BTS Bangchak \u0e41\u0e25\u0e30 BTS Punnawithi",
          "officeName": "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e0a\u0e47\u0e2d\u0e04\u0e42\u0e01\u0e49 \u0e04\u0e32\u0e23\u0e4c\u0e14 \u0e40\u0e2d\u0e47\u0e19\u0e40\u0e15\u0e2d\u0e23\u0e4c\u0e44\u0e1e\u0e23\u0e2a\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14",
          "openForCooperativeInternship": true,
          "openingDetailContactChannel": "hr@chococrm.com",
          "openingId": 1055,
          "quota": 1,
          "recruitmentContactChannel": "hr@chococrm.com",
          "requirements": "<ul><li>Flexible working hours, regular office hours are 09:00 AM to 6:00 PM, Monday to Friday</li><li>Hybrid working policy</li><li>Startup working culture and environment</li><li>Work with modern technologies and experienced colleagues</li></ul>",
          "startDate": "2026-04-30T17:00:00.000Z",
          "tags": [
            {
              "tagId": 7,
              "tagName": "C#"
            },
            {
              "tagId": 29,
              "tagName": "SQL"
            },
            {
              "tagId": 36,
              "tagName": "Backend"
            },
            {
              "tagId": 41,
              "tagName": "Developer"
            },
            {
              "tagId": 52,
              "tagName": ".Net Core"
            },
            {
              "tagId": 58,
              "tagName": "web application"
            },
            {
              "tagId": 124,
              "tagName": "CRM"
            },
            {
              "tagId": 126,
              "tagName": "Web Developer"
            },
            {
              "tagId": 139,
              "tagName": "API"
            },
            {
              "tagId": 203,
              "tagName": "CDP"
            },
            {
              "tagId": 405,
              "tagName": "POS"
            }
          ],
          "title": "Backend Developer ",
          "workingCondition": "Hybrid"
        },
        {
          "company": {
            "companyId": 114,
            "companyNameEn": "gofive",
            "companyNameTh": "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e42\u0e01\u0e44\u0e1f\u0e27\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14",
            "facebook": "https://tr.ee/HJ0sTKLVqr",
            "line": "https://tr.ee/HQ52THm4rA",
            "logoUrl": "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/2bd29582-0e91-4255-9b17-64ab0d6ff00e?v=1734247862970",
            "website": "https://www.gofive.co.th"
          },
          "compensationAmount": 200.0,
          "compensationType": {
            "compensationType": "\u0e1a\u0e32\u0e17/\u0e27\u0e31\u0e19",
            "compensationTypeId": 1
          },
          "description": "<p><strong style=\"color: rgb(28, 28, 34);\">Job Overview</strong></p><p>Ready to launch your QA superpowers? \ud83d\ude80 Join Gofive as an Automation Tester Intern and help build software that people <em>love</em> to use. You\u2019ll design and run real test cases, spin up slick automation (hello, Playwright!), dip your toes into performance testing, and be part of a squad that ships with confidence. Come learn fast, ship smart, and make your mark.</p><p><br></p><p><strong>What you'll learn:</strong></p><ol><li>Practical test design techniques (boundary, equivalence, risk-based testing).</li><li>Automation frameworks (Playwright), API testing workflows, and CI basics.</li><li>Performance testing fundamentals (workload modeling, metrics like latency/throughput).</li><li>Defect lifecycle and crisp communication with engineers and product partners.</li><li>How product, design, and engineering work together to deliver high-quality releases.</li></ol><p><br></p><p><strong style=\"color: rgb(28, 28, 34);\">Responsibilities</strong></p><ol><li>Co-create and execute system test cases to prove our features work flawlessly (and break things the <em>right</em> way).</li><li>Capture test results like a pro and share crisp, actionable feedback with devs.</li><li>Craft functional &amp; non-functional test cases for each sprint\u2014mentored, but with real ownership.</li><li>Log bugs with clear steps, evidence (screenshots/vids), and expected vs. actual\u2014no mysteries left behind.</li><li>Build and run UI automation (Playwright) and API automation to boost coverage and speed.</li><li>Join design chats to sprinkle QA magic on UX/UI, tech tasks, and user stories.</li><li>Keep a pulse on production: watch dashboards/logs, spot issues early, and help verify fixes.</li><li>Try your hand at performance testing with JMeter (plus exposure to LoadRunner) and learn how to read the signals.</li><li>Team up with developers, product owners, and designers in our agile rhythm to squash issues fast.</li><li>Help plan and run UAT\u2014test data, scenarios, checklists, and smooth sign-off.</li></ol><p><br></p><p><strong style=\"color: rgb(28, 28, 34);\">Qualifications</strong></p><ol><li>Pursuing or recently finished a Bachelor\u2019s in Computer Engineering/Computer Science (or related).</li><li>Know the testing basics (test cases, regression, defect reporting); project/coursework/internship experience is a bonus.</li><li>Curious about automation &amp; performance tools\u2014Playwright, Postman/REST, JMeter (learning mindset &gt; years of experience).</li><li>Exposure to coding, business, or design earns extra credit.</li><li>Comfortable with SQL fundamentals (SELECTs, JOINs) is a plus.</li><li>A proactive team player who thrives in fast-moving spaces\u2014ask great questions, take feedback, level up.</li><li>Thai &amp; English communication\u2014clear, friendly, and professional.</li></ol><p><br></p>",
          "endDate": null,
          "inStudentDraftCount": 1,
          "isAcceptingApplication": true,
          "latitude": 13.7205558,
          "longitude": 100.5599961,
          "officeAddressLine1": "\u0e2d\u0e32\u0e04\u0e32\u0e23 FYI Center, Tower 2 \u0e0a\u0e31\u0e49\u0e19 12th Floor \u0e2b\u0e49\u0e2d\u0e07 Unit 1203-1205, \u0e40\u0e25\u0e02\u0e17\u0e35\u0e48 2525 \u0e16\u0e19\u0e19 Rama IV Rd, \u0e41\u0e02\u0e27\u0e07 Khlong Toei \u0e40\u0e02\u0e15 Khlong Toei \u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14 Bangkok 10110",
          "officeAddressLine2": "",
          "officeName": "\u0e2a\u0e32\u0e02\u0e32 FYI Center (\u0e1e\u0e23\u0e30\u0e23\u0e32\u0e21\u0e17\u0e35\u0e48 4) ",
          "openForCooperativeInternship": true,
          "openingDetailContactChannel": "Email: Work@gofive.co.th\nDM Gofive Social Media - all channels: https://linktr.ee/gofive_family\n",
          "openingId": 1072,
          "quota": 1,
          "recruitmentContactChannel": "https://jobs.empeo.com/Gofive/245717",
          "requirements": null,
          "startDate": null,
          "tags": [
            {
              "tagId": 64,
              "tagName": "automated testing"
            },
            {
              "tagId": 280,
              "tagName": "playwright"
            },
            {
              "tagId": 408,
              "tagName": "Postman"
            },
            {
              "tagId": 409,
              "tagName": "JMeter"
            }
          ],
          "title": "Internship Automate Tester",
          "workingCondition": "On-Site"
        },
        {
          "company": {
            "companyId": 114,
            "companyNameEn": "gofive",
            "companyNameTh": "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e42\u0e01\u0e44\u0e1f\u0e27\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14",
            "facebook": "https://tr.ee/HJ0sTKLVqr",
            "line": "https://tr.ee/HQ52THm4rA",
            "logoUrl": "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/2bd29582-0e91-4255-9b17-64ab0d6ff00e?v=1734247862970",
            "website": "https://www.gofive.co.th"
          },
          "compensationAmount": NaN,
          "compensationType": null,
          "description": "<p><strong style=\"color: rgb(28, 28, 34);\">Job Overview</strong></p><p>We are looking for a Flutter Mobile Developer Intern to join our team and gain hands-on experience in developing and maintaining mobile applications. As an intern, you will collaborate with our developers, designers, and product managers to learn best practices in mobile app development, improve your coding skills, and understand the full software development life cycle (SDLC).</p><p><br></p><p><strong style=\"color: rgb(28, 28, 34);\">Responsibilities</strong></p><ol><li>Assist in developing and maintaining mobile applications using Flutter and Dart.</li><li>Collaborate with cross-functional teams to deliver quality software.</li><li>Learn and apply software development best practices (Clean Architecture, MVC, MVVM).</li><li>Write clean and testable code under guidance from senior developers.</li><li>Participate in testing, debugging, and troubleshooting for smooth user experiences.</li><li>Contribute to code reviews and learn from feedback.</li><li>Stay updated with new technologies and trends in mobile development.</li></ol><p><br></p><p><strong style=\"color: rgb(28, 28, 34);\">Qualifications</strong></p><ol><li>Basic knowledge of Flutter and Dart.</li><li>Familiarity with mobile app development principles (Android or iOS).</li><li>Interest in Clean Architecture, MVC, or MVVM is a plus.</li><li>Knowledge of CI/CD, DevOps, or app deployment is a bonus.</li><li>Eagerness to learn and take on new challenges.</li><li>Ability to work independently and as part of a team.</li><li>Good problem-solving skills and attention to detail.</li><li>Familiarity with Agile methodologies is a plus.</li><li>Open to new graduates or students in their 1st - final year.</li></ol>",
          "endDate": null,
          "inStudentDraftCount": 0,
          "isAcceptingApplication": true,
          "latitude": 13.7205558,
          "longitude": 100.5599961,
          "officeAddressLine1": "\u0e2d\u0e32\u0e04\u0e32\u0e23 FYI Center, Tower 2 \u0e0a\u0e31\u0e49\u0e19 12th Floor \u0e2b\u0e49\u0e2d\u0e07 Unit 1203-1205, \u0e40\u0e25\u0e02\u0e17\u0e35\u0e48 2525 \u0e16\u0e19\u0e19 Rama IV Rd, \u0e41\u0e02\u0e27\u0e07 Khlong Toei \u0e40\u0e02\u0e15 Khlong Toei \u0e08\u0e31\u0e07\u0e2b\u0e27\u0e31\u0e14 Bangkok 10110",
          "officeAddressLine2": "",
          "officeName": "\u0e2a\u0e32\u0e02\u0e32 FYI Center (\u0e1e\u0e23\u0e30\u0e23\u0e32\u0e21\u0e17\u0e35\u0e48 4) ",
          "openForCooperativeInternship": true,
          "openingDetailContactChannel": "Email: Work@gofive.co.th\nDM Gofive Social Media - all channels: https://linktr.ee/gofive_family\n",
          "openingId": 1075,
          "quota": 2,
          "recruitmentContactChannel": "https://jobs.empeo.com/Gofive/249298",
          "requirements": null,
          "startDate": null,
          "tags": [],
          "title": "Internship Flutter Mobile Developer",
          "workingCondition": null
        },
        {
          "company": {
            "companyId": 114,
            "companyNameEn": "gofive",
            "companyNameTh": "\u0e1a\u0e23\u0e34\u0e29\u0e31\u0e17 \u0e42\u0e01\u0e44\u0e1f\u0e27\u0e4c \u0e08\u0e33\u0e01\u0e31\u0e14",
            "facebook": "https://tr.ee/HJ0sTKLVqr",
            "line": "https://tr.ee/HQ52THm4rA",
            "logoUrl": "https://cedtintern.cp.eng.chula.ac.th/api/common/files/company/logo/2bd29582-0e91-4255-9b17-64ab0d6ff00e?v=1734247862970",
            "website": "https://www.gofive.co.th"
          },
          "compensationAmount": NaN,
          "compensationType": null,

# Search Location On old data

In [ ]:
old_df = pd.read_json('application_list.json')

In [ ]:
old_df.isna().sum()

openingId                         0
company                           0
title                             0
description                       5
quota                             0
openForCooperativeInternship      0
compensationAmount               92
compensationType                 82
workingCondition                 23
requirements                    114
tags                              0
officeName                        0
officeAddressLine1                0
officeAddressLine2                0
recruitmentContactChannel         0
openingDetailContactChannel       0
startDate                       129
endDate                         129
isAcceptingApplication            0
inStudentDraftCount               0
latitude                          8
longitude                         8
dtype: int64

In [ ]:
missing_idx = old_df['longitude'].isna()
missing_df = old_df[missing_idx]

address_group = missing_df.groupby('officeAddressLine1')

address_df = pd.DataFrame(data=[],columns=['address', 'longitude', 'latitude'])
for address, _ in address_group:
  coords = search_location(address, verbose=True)
  row = pd.DataFrame(data=[[address, coords[0], coords[1]]], columns=['address', 'longitude', 'latitude'])
  address_df = pd.concat([address_df, row], axis=0, copy=False)

for _, row in address_df.iterrows():
  filter_idx = missing_df['officeAddressLine1'] == row['address']
  missing_df.loc[filter_idx, ['latitude', 'longitude']] = [row['latitude'], row['longitude']]

old_df.loc[missing_idx, ['longitude', 'latitude']] =  missing_df[['longitude','latitude']]

Location Extract Result [100.5592531, 13.807463900000002]
)]}'
[["https://maps.app.goo.gl/ij647WutDkaHxp7t5",[[null,null,null,null,null,null,null,null,"DOE6aejSF9Xi1e8P6uv--A8","0ahUKEwjoiN3j6rWRAxVVcfUHHeq1H_8QmBkIAigA",null,null,["0ahUKEwjoiN3j6rWRAxVVcfUHHeq1H_8Q42oIAygA","/search?q\u003dhttps://maps.app.goo.gl/ij647WutDkaHxp7t5\u0026hl\u003dth\u0026authuser\u003d0"],null,null,null,null,null,[]]],null,null,null,null,null,null,null,null,null,0],null,null,null,null,null,null,"DOE6aejSF9Xi1e8P6uv--A8",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,[2],null,null,null,null,null,null,null,"Q2dBd0Fn",null,null,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,[0],null,null,null,null,null,null,null,"0ahUKEwjoiN3j6rWRAxVVcfUHHeq1H_8QmRkIAQ"]

/tmp/ipython-input-838100418.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  address_df = pd.concat([address_df, row], axis=0, copy=False)

In [ ]:
old_df.loc[missing_idx]

,openingId,company,title,description,quota,openForCooperativeInternship,compensationAmount,compensationType,workingCondition,requirements,...,officeAddressLine1,officeAddressLine2,recruitmentContactChannel,openingDetailContactChannel,startDate,endDate,isAcceptingApplication,inStudentDraftCount,latitude,longitude
37,1150,"{'companyId': 23, 'companyNameTh': 'บริษัท เอ็...",Full Stack Developer Internship,<h2><strong>About This Role :</strong></h2><p>...,2,False,150.0,"{'compensationTypeId': 1, 'compensationType': ...",On-Site,None,...,S-Oasis 21fl.,อาคาร S-Oasis ชั้น 21 ตรงข้ามสวนจตุจักร ใกล้ B...,02-821-7999 ต่อ 8 ต่อ 2,02-821-7999 ต่อ 8 ต่อ 2,2026-05-03T17:00:00.000Z,2026-07-29T17:00:00.000Z,True,0,13.807464,100.559253
38,1152,"{'companyId': 23, 'companyNameTh': 'บริษัท เอ็...",IT Operations Specialist Internship,<p><strong>Job Descriptions :</strong></p><ul>...,1,False,150.0,"{'compensationTypeId': 1, 'compensationType': ...",On-Site,None,...,S-Oasis 21fl.,อาคาร S-Oasis ชั้น 21 ตรงข้ามสวนจตุจักร ใกล้ B...,02-821-7999 ต่อ 8 ต่อ 2,02-821-7999 ต่อ 8 ต่อ 2,2026-04-30T17:00:00.000Z,2026-07-29T17:00:00.000Z,True,0,13.807464,100.559253
50,1178,"{'companyId': 53, 'companyNameTh': 'บริษัท ปูน...","Data Science Intern, Rayong Base (SCGC)",<h2><br></h2><h2><strong>Responsibilities:</st...,1,False,500.0,"{'compensationTypeId': 1, 'compensationType': ...",On-Site,<p><br></p><ul><li>ปฎิบัติงานที่จังหวัดระยอง บ...,...,https://maps.app.goo.gl/ij647WutDkaHxp7t5,,Project Assistant \nWirakarn Karwichai (มัดหมี...,,None,None,True,7,NaN,NaN
184,1475,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",Application Development,<ul><li>ร่วมพัฒนา ออกแบบ และปรับปรุงแอปพลิเคชั...,10,True,500.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,9,NaN,NaN
185,1476,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",Data Management,<h2><strong>Data Engineer (DE)</strong></h2><u...,15,True,400.0,"{'compensationTypeId': 1, 'compensationType': ...",None,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,12,NaN,NaN
186,1478,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",Business Analyst,<ul><li>ร่วมเก็บรวบรวมและวิเคราะห์ความต้องการข...,3,True,400.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,5,NaN,NaN
187,1480,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",IOT Engineer,<ul><li>สนับสนุนทีม IoT ในการพัฒนาและทดสอบโซลู...,5,True,400.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,4,NaN,NaN
188,1481,"{'companyId': 148, 'companyNameTh': 'บริษัท ที...",UX/UI Designer,<ul><li>ร่วมวิเคราะห์ความต้องการของผู้ใช้ (Use...,4,True,400.0,"{'compensationTypeId': 1, 'compensationType': ...",Hybrid,None,...,ไม่ระบุ,,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,Phone : 093-5747-629\nE-Mail : Sasitorn.San@...,None,None,True,5,NaN,NaN

In [ ]:
old_df.isna().sum()

openingId                         0
company                           0
title                             0
description                       5
quota                             0
openForCooperativeInternship      0
compensationAmount               92
compensationType                 82
workingCondition                 23
requirements                    114
tags                              0
officeName                        0
officeAddressLine1                0
officeAddressLine2                0
recruitmentContactChannel         0
openingDetailContactChannel       0
startDate                       129
endDate                         129
isAcceptingApplication            0
inStudentDraftCount               0
latitude                          6
longitude                         6
dtype: int64

In [ ]:
old_df.to_json('application_list.json', orient='records')